# config.yaml — フルオプション例（このままコピペして用途に合わせて調整）

# 正規化対象列（1オリジン）— 例: 1列目=題目, 2列目=著者
columns: [1, 2]

# 入出力の文字コード
code_page: utf8           # utf8 | cp932
has_header: true          # 先頭行がヘッダなら true

# 出力フォーマット
output:
  line_ending: crlf       # crlf(既定) | lf
  utf8_bom: true          # UTF-8 のとき BOM を付けるか（既定 true, cp932 では無視）

# ログ
log:
  level: info             # trace|debug|info|warn|error|fatal|panic
  output: stdout          # stdout|stderr|<path/to/logfile>

# 正規化オプション
normalize:
  # 文字種・幅・ケース
  to_upper: false
  to_lower: true
  half_kana_to_full: false
  full_kana_to_half: false
  full_digit_to_half: true
  paren_num_to_half: true
  dash_to_hyphen: false          # trueだとハイフン類を"-"に統一, falseなら下の remove_chars で削除推奨

  # 構文要素の除去
  remove_parens: true            # 各種カッコの除去
  remove_html: false             # すべての <...> を削除する（タグ本体のみ。属性含む）
  remove_html_tags: [u, i, br]   # 特定タグだけ除去（中身は保持）。大小文字は不問
  remove_substrings:             # リテラル一致で除去（属性付きタグは残したい等の用途）
    - "<sup>"                    
    - "</sup>"
    - "<sub>"
    - "</sub>"

  # 非印刷制御
  remove_non_printable: false    # Cc/Cf を一括削除
  remove_crlf_only: true         # CR/LF だけ削除（上と独立して動作）

  # 一括カテゴリ削除（必要に応じて）
  remove_punctuation: false      # Unicode P*（句読点・括弧など）
  remove_symbols: false          # Unicode S*（記号。通貨記号なども含む）
  remove_emoji: false            # 代表的な絵文字ブロック＋ZWJ/VS-16/肌色修飾

  # 正規化値の書き戻し
  write_back: false              # true: 対象列を正規化後で上書き / false: 元列は保持（キー生成だけ正規化したいとき）

  # 個別文字の削除（集合の配列 or 文字列）— 例示（必要に応じて削る/足す）
  remove_chars:
    - "-–—―‐ｰー－"             # ハイフン類
    - "\u3000\u2000\u00A0"     # 全角/EN SPACE/NBSP
    - "『』「」｢｣（）()[]<>【】《》≪≫"  # 括弧類
    - "、。，．,.;；:"             # 句読点類
    - "/"                        # スラッシュ
    # 引用符類（コードポイント指定例）
    - "\u0022\u201C\u201D\u2018\u2019\u0060\u309B"
